<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Http;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = collect([
            [
                'postcode' => 'LA17 7UY',
                'open_Monday' => '09:00',
                'open_Tuesday' => '10:00',
                'open_Wednesday' => '',
                'open_Thursday' => '10:00',
                'open_Friday' => '',
                'open_Saturday' => '10:00',
                'open_Sunday' => '09:00',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '19:00',
                'closed_Wednesday' => '',
                'closed_Thursday' => '19:00',
                'closed_Friday' => '',
                'closed_Saturday' => '19:00',
                'closed_Sunday' => '16:00',
            ],
            [
                'postcode' => 'LL27 0YX',
                'open_Monday' => '09:00',
                'open_Tuesday' => '09:00',
                'open_Wednesday' => '',
                'open_Thursday' => '',
                'open_Friday' => '09:00',
                'open_Saturday' => '09:00',
                'open_Sunday' => '09:00',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '16:00',
                'closed_Wednesday' => '',
                'closed_Thursday' => '',
                'closed_Friday' => '16:00',
                'closed_Saturday' => '16:00',
                'closed_Sunday' => '16:00',
            ],
            [
                'postcode' => 'M46 9PU',
                'open_Monday' => '08:30',
                'open_Tuesday' => '09:00',
                'open_Wednesday' => '08:30',
                'open_Thursday' => '08:30',
                'open_Friday' => '08:30',
                'open_Saturday' => '08:30',
                'open_Sunday' => '08:30',
                'closed_Monday' => '17:30',
                'closed_Tuesday' => '16:00',
                'closed_Wednesday' => '17:30',
                'closed_Thursday' => '17:30',
                'closed_Friday' => '17:30',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '17:30',
            ],
            [
                'postcode' => 'NE68 7TQ',
                'open_Monday' => '',
                'open_Tuesday' => '',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '',
                'open_Friday' => '',
                'open_Saturday' => '08:30',
                'open_Sunday' => '08:30',
                'closed_Monday' => '',
                'closed_Tuesday' => '',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '',
                'closed_Friday' => '',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '17:30',
            ],
            [
                'postcode' => 'WN6 0QG',
                'open_Monday' => '',
                'open_Tuesday' => '10:00',
                'open_Wednesday' => '10:00',
                'open_Thursday' => '09:00',
                'open_Friday' => '10:00',
                'open_Saturday' => '',
                'open_Sunday' => '',
                'closed_Monday' => '',
                'closed_Tuesday' => '19:00',
                'closed_Wednesday' => '19:00',
                'closed_Thursday' => '16:00',
                'closed_Friday' => '19:00',
                'closed_Saturday' => '',
                'closed_Sunday' => '',
            ],
            [
                'postcode' => 'SE9 1QR',
                'open_Monday' => '08:30',
                'open_Tuesday' => '08:30',
                'open_Wednesday' => '08:30',
                'open_Thursday' => '08:30',
                'open_Friday' => '08:30',
                'open_Saturday' => '08:30',
                'open_Sunday' => '08:30',
                'closed_Monday' => '17:30',
                'closed_Tuesday' => '17:30',
                'closed_Wednesday' => '17:30',
                'closed_Thursday' => '17:30',
                'closed_Friday' => '17:30',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '17:30',
            ],
            [
                'postcode' => 'OL8 4NJ',
                'open_Monday' => '09:00',
                'open_Tuesday' => '09:00',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '',
                'open_Friday' => '08:30',
                'open_Saturday' => '08:30',
                'open_Sunday' => '',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '16:00',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '',
                'closed_Friday' => '17:30',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '',
            ],
            [
                'postcode' => 'UB5 6NQ',
                'open_Monday' => '09:00',
                'open_Tuesday' => '09:00',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '',
                'open_Friday' => '',
                'open_Saturday' => '08:30',
                'open_Sunday' => '08:30',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '16:00',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '',
                'closed_Friday' => '',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '17:30',
            ],
            [
                'postcode' => 'PA3 1BT',
                'open_Monday' => '09:00',
                'open_Tuesday' => '09:00',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '08:30',
                'open_Friday' => '08:30',
                'open_Saturday' => '',
                'open_Sunday' => '',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '16:00',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '17:30',
                'closed_Friday' => '17:30',
                'closed_Saturday' => '',
                'closed_Sunday' => '',
            ],
            [
                'postcode' => 'EH17 8BB',
                'open_Monday' => '08:30',
                'open_Tuesday' => '08:30',
                'open_Wednesday' => '',
                'open_Thursday' => '',
                'open_Friday' => '09:00',
                'open_Saturday' => '09:00',
                'open_Sunday' => '',
                'closed_Monday' => '17:30',
                'closed_Tuesday' => '17:30',
                'closed_Wednesday' => '',
                'closed_Thursday' => '',
                'closed_Friday' => '16:00',
                'closed_Saturday' => '16:00',
                'closed_Sunday' => '',
            ],
            [
                'postcode' => 'EH5 1JS',
                'open_Monday' => '09:00',
                'open_Tuesday' => '08:30',
                'open_Wednesday' => '08:30',
                'open_Thursday' => '',
                'open_Friday' => '09:00',
                'open_Saturday' => '',
                'open_Sunday' => '09:00',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '17:30',
                'closed_Wednesday' => '17:30',
                'closed_Thursday' => '',
                'closed_Friday' => '16:00',
                'closed_Saturday' => '',
                'closed_Sunday' => '16:00',
            ],
            [
                'postcode' => 'S17 3LT',
                'open_Monday' => '09:00',
                'open_Tuesday' => '',
                'open_Wednesday' => '08:30',
                'open_Thursday' => '08:30',
                'open_Friday' => '',
                'open_Saturday' => '',
                'open_Sunday' => '09:00',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '',
                'closed_Wednesday' => '17:30',
                'closed_Thursday' => '17:30',
                'closed_Friday' => '',
                'closed_Saturday' => '',
                'closed_Sunday' => '16:00',
            ],
            [
                'postcode' => 'HD4 7LT',
                'open_Monday' => '09:00',
                'open_Tuesday' => '',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '08:30',
                'open_Friday' => '08:30',
                'open_Saturday' => '',
                'open_Sunday' => '',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '17:30',
                'closed_Friday' => '17:30',
                'closed_Saturday' => '',
                'closed_Sunday' => '',
            ],
            [
                'postcode' => 'NE4 6BP',
                'open_Monday' => '09:00',
                'open_Tuesday' => '',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '',
                'open_Friday' => '08:30',
                'open_Saturday' => '08:30',
                'open_Sunday' => '',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '',
                'closed_Friday' => '17:30',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '',
            ],
            [
                'postcode' => 'CH45 0JS',
                'open_Monday' => '09:00',
                'open_Tuesday' => '',
                'open_Wednesday' => '',
                'open_Thursday' => '09:00',
                'open_Friday' => '',
                'open_Saturday' => '08:30',
                'open_Sunday' => '08:30',
                'closed_Monday' => '16:00',
                'closed_Tuesday' => '',
                'closed_Wednesday' => '',
                'closed_Thursday' => '16:00',
                'closed_Friday' => '',
                'closed_Saturday' => '17:30',
                'closed_Sunday' => '17:30',
            ],
            [
                'postcode' => 'CT15 6JJ',
                'open_Monday' => '08:30',
                'open_Tuesday' => '',
                'open_Wednesday' => '09:00',
                'open_Thursday' => '',
                'open_Friday' => '',
                'open_Saturday' => '',
                'open_Sunday' => '08:30',
                'closed_Monday' => '17:30',
                'closed_Tuesday' => '',
                'closed_Wednesday' => '16:00',
                'closed_Thursday' => '',
                'closed_Friday' => '',
                'closed_Saturday' => '',
                'closed_Sunday' => '17:30',
            ],
        ]);

        $postcodes = $this->getLocation($locations->pluck('postcode'));

        foreach ($locations as $location) {
            [
                'postcode' => $postcode,
                'latitude' => $latitude,
                'longitude' => $longitude,
            ] = $postcodes['result'][array_search($location['postcode'], array_column($postcodes['result'], 'query'))]['result'];

            \App\Models\Location::factory()->create([
                'postcode' => $postcode,
                'times' => [
                    'opening_times' => [
                        'monday' => $location['open_Monday'],
                        'tuesday' => $location['open_Tuesday'],
                        'wednesday' => $location['open_Wednesday'],
                        'thursday' => $location['open_Thursday'],
                        'friday' => $location['open_Friday'],
                        'saturday' => $location['open_Saturday'],
                        'sunday' => $location['open_Sunday'],
                    ],
                    'closing_times' => [
                        'monday' => $location['closed_Monday'],
                        'tuesday' => $location['closed_Tuesday'],
                        'wednesday' => $location['closed_Wednesday'],
                        'thursday' => $location['closed_Thursday'],
                        'friday' => $location['closed_Friday'],
                        'saturday' => $location['closed_Saturday'],
                        'sunday' => $location['closed_Sunday'],
                    ],
                ],
                'latitude' => $latitude,
                'longitude' => $longitude,
            ]);
        }
    }

    public function getLocation(Collection $postcodes):? Collection
    {
        try {
            $response = Http::post('https://api.postcodes.io/postcodes/', [
                'postcodes' => $postcodes,
            ])->throw()->collect();

            return $response;
        } catch (\Exception) {
            return null;
        }
    }
}
